#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-enchant-soname1
Version  : 1.6.1
Release  : 3
URL      : https://github.com/AbiWord/enchant/releases/download/enchant-1-6-1/enchant-1.6.1.tar.gz
Source0  : https://github.com/AbiWord/enchant/releases/download/enchant-1-6-1/enchant-1.6.1.tar.gz
Summary  : An Enchanting Spell Checking Library
Group    : Development/Tools
License  : LGPL-2.1
Requires: compat-enchant-soname1-bin
Requires: compat-enchant-soname1-lib
Requires: compat-enchant-soname1-license
Requires: compat-enchant-soname1-data
Requires: compat-enchant-soname1-man
BuildRequires : aspell-dev
BuildRequires : hunspell-dev
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(hunspell)

%description
A library that wraps other spell checking backends.

%package bin
Summary: bin components for the compat-enchant-soname1 package.
Group: Binaries
Requires: compat-enchant-soname1-data = %{version}-%{release}
Requires: compat-enchant-soname1-license = %{version}-%{release}
Requires: compat-enchant-soname1-man = %{version}-%{release}

%description bin
bin components for the compat-enchant-soname1 package.


%package data
Summary: data components for the compat-enchant-soname1 package.
Group: Data

%description data
data components for the compat-enchant-soname1 package.


%package dev
Summary: dev components for the compat-enchant-soname1 package.
Group: Development
Requires: compat-enchant-soname1-lib = %{version}-%{release}
Requires: compat-enchant-soname1-bin = %{version}-%{release}
Requires: compat-enchant-soname1-data = %{version}-%{release}
Provides: compat-enchant-soname1-devel = %{version}-%{release}

%description dev
dev components for the compat-enchant-soname1 package.


%package lib
Summary: lib components for the compat-enchant-soname1 package.
Group: Libraries
Requires: compat-enchant-soname1-data = %{version}-%{release}
Requires: compat-enchant-soname1-license = %{version}-%{release}

%description lib
lib components for the compat-enchant-soname1 package.


%package license
Summary: license components for the compat-enchant-soname1 package.
Group: Default

%description license
license components for the compat-enchant-soname1 package.


%package man
Summary: man components for the compat-enchant-soname1 package.
Group: Default

%description man
man components for the compat-enchant-soname1 package.


%prep
%setup -q -n enchant-1.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537647506
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1537647506
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/compat-enchant-soname1
cp COPYING.LIB %{buildroot}/usr/share/doc/compat-enchant-soname1/COPYING.LIB
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/enchant
/usr/bin/enchant-lsmod

%files data
%defattr(-,root,root,-)
%exclude /usr/share/enchant/enchant.ordering

%files dev
%defattr(-,root,root,-)
/usr/include/enchant/enchant++.h
/usr/include/enchant/enchant-provider.h
/usr/include/enchant/enchant.h
/usr/lib64/libenchant.so
/usr/lib64/pkgconfig/enchant.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/enchant/libenchant_aspell.so
/usr/lib64/enchant/libenchant_ispell.so
/usr/lib64/enchant/libenchant_myspell.so
/usr/lib64/enchant/libenchant_zemberek.so
/usr/lib64/libenchant.so.1
/usr/lib64/libenchant.so.1.6.1

%files license
%defattr(-,root,root,-)
/usr/share/doc/compat-enchant-soname1/COPYING.LIB

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/enchant.1
